---
title: "Current & Past Work"
output: html_document
---
```{r, child="_setup.Rmd"}
```

## Ongoing Research

|

* Dello Stritto, M. E., Heiser, R., Brown, A., Croft, B. “Issues of bias & equity in the uses of learner data.” (Manuscript in progress)
* Rives, A. & Brown, A. “Wake Forest’s ChemBook: Producing bite-size text and videos for presenting thermochemistry,” (Manuscript in progress)

|
|

## Selected Presentations, Posts, & Projects

|
|

### OSU Ecampus Learning Analytics Cohort
One of 12 participating researchers in the Perceptions of Learning Data in Higher Education study. This interview-based study collected information about student, faculty, staff, and administrator views of how data is used to understand the student experience or to improve student learning in higher education. The project was designed with a systems perspective in mind in order to explore benefits and challenges of the use of learning and learner data, ethics and privacy issues and concerns among different stakeholder groups, and ideas and perceptions regarding the current and future uses of learning and learner data.
*[Findings from the Perceptions of Learning Data in Higher Education](https://ecampus.oregonstate.edu/research/study/learning-analytics/results.htm)*

|
### Course Workload Estimator
I joined with Betsy Barre and Justin Esarey to modify their course workload estimator. The enhanced estimator includes additional fields particularly salient to online course designs.
*[Course Workload Estimator 2.0](https://cat.wfu.edu/resources/tools/estimator2)*

|

### Chunking Content, Online Course Design
I received an invitation to present to the faculty of the School of Law in preparation for online and remote instruction in Fall 2020. I was tasked with delivering a webinar that addressed3 the theory and practice behind segmenting instructional content for online and digital learning environments. 
<details>
  <summary>**Expand to View**</summary>
<iframe src="https://player.vimeo.com/video/437171592?h=c5bcd8c736" width="640" height="354" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
</details>
|
|

### Blog Posts [selected]
* [Building the Online Learning Community](https://cat.wfu.edu/2020/04/onlinecommunity/#) (April 2020). Center for the Advancement of Teaching Blog.
* [Scratching an Itch](https://oe.wfu.edu/2019/02/scratching-an-itch/) (February 2019). Office of Online Education Blog.
* [Human-centered Instructional Design](https://oe.wfu.edu/2019/02/human-centered-instructional-design/) (February 2019). Office of Online Education Blog.
* [Building the Ship while Sailing: Faculty Learning Communities and Technology](https://www.facultyfocus.com/articles/faculty-development/faculty-learning-communities-technology/) (Feburary 2018). Faculty Focus, Magna Publications.
